---
apiVersion: v1
kind: Service
metadata:
  name: algorand
  labels:
    app: algorand
spec:
  clusterIP: None
  selector:
    app: algorand
  ports:
  - name: algod
    port: 4001
    targetPort: algod
  - name: kmd
    port: 4002
    targetPort: kmd
  - name: indexer
    port: 4003
    targetPort: indexer
  - name: postgres
    port: 5432
    targetPort: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: algorand
spec:
  selector:
    matchLabels:
      app: algorand
  template:
    metadata:
      labels:
        app: algorand
    spec:
      containers:
      - name: algod
        image: algo_testnet
        command:
          - /bin/sh
          - -c
          - ./goal network start -r /network && sleep infinity
        ports:
          - containerPort: 4001
            name: algod
            protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 4001
          initialDelaySeconds: 3
      - name: goal-kmd
        image: algo_testnet
        command:
          - /bin/sh
          - -c
          - ./goal kmd start -d /network/Node && ./goal account list -d /network/Node && sleep infinity
        ports:
          - containerPort: 4002
            name: kmd
            protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 4002
          initialDelaySeconds: 3
      - name: indexer
        image: algo_indexer
        command:
          - /bin/sh
          - -c
          - ./run_indexer.sh
        ports:
          - containerPort: 4003
            name: indexer
            protocol: TCP
        #readinessProbe:
        #  tcpSocket:
        #    port: 4002
        #  initialDelaySeconds: 3
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5234
            name: postgres
            protocol: TCP
        env:
          - name: POSTGRES_USER
            value: algorand
          - name: POSTGRES_PASSWORD
            value: indexer
          - name: POSTGRES_DB
            value: pgdb
        #readinessProbe:
        #  tcpSocket:
        #    port: 4002
        #  initialDelaySeconds: 3
