FROM docker.io/algorand/stable:3.2.1@sha256:0a87978492680fd98e2cc410f59f2bfd7fef979f035eb060685d56a6e916b5bd

RUN mkdir -p /setup
ADD goal_template.json /setup/

RUN ./goal network create -n sandnet -r /network -t /setup/goal_template.json && echo rawr

ADD algod.token /network/Node/algod.token
ADD node_config.json /network/Node/config.json
ADD kmd.token /network/Node/kmd-v0.5/kmd.token
ADD kmd_config.json /network/Node/kmd-v0.5/kmd_config.json

