FROM docker.io/algorand/stable:3.5.1@sha256:734c230ace50b8e8d706e2aa072c4f761a2442d9922a13b9ab41676637edc1fc

RUN mkdir -p /setup
ADD goal_template.json /setup/

RUN ./goal network create -n sandnet -r /network -t /setup/goal_template.json && echo rawr

ADD algod.token /network/Node/algod.token
ADD node_config.json /network/Node/config.json
ADD kmd.token /network/Node/kmd-v0.5/kmd.token
ADD kmd_config.json /network/Node/kmd-v0.5/kmd_config.json

